### ISSUE TITLE
[Feature Request] Customizable ping icons

### ISSUE THREAD

**Issue by xllifi** [LukenSkyne/Minecraft-Ping-Wheel#10]
- Add a texture to ping icon
- Add an icon size slider in mod settings

For example, I want the default ping to look like this:
<img src="https://github.com/LukenSkyne/Minecraft-Ping-Wheel/assets/70767436/3389fe83-b33f-4f2c-b7fa-c970648709d1" height=300>
This result can be achieved by modifying size and texture

**Comment by ThatIsAPseudo** [comment]
Could there be keybinds for different icons ? For instance "M" for a "Pickaxe" icon, "P" for a "block" icon, etc

**Comment by xllifi** [comment]
I'd much prefer radial menu when you hold the button (like in apex)

This mod should copy everything from Apex IMO, respawn made an exemplary communication system

**Comment by LukenSkyne** [comment]
As soon as there are different kinds of pings, there is going to be a radial menu aka ping wheel :P
