### ISSUE TITLE
Bukkit implementation

### ISSUE THREAD

**Issue by ghost** [LukenSkyne/Minecraft-Ping-Wheel#11]
Hi,
I noticed that this mod does not support Bukkit servers, so I wrote my own plugin implementation with extensive configuration.
Here it is: https://github.com/SandResidence/PingWheelBukkit

**Comment by RXJpaw** [comment]
Cool idea! I will definitely test this when i next play Minecraft.
What I found is that it seems to be limited to [papermc](https://github.com/PaperMC/Paper). As found [here](https://github.com/SandResidence/PingWheelBukkit/blob/main/src/main/java/me/axerr/pingwheel/PingWheel.java#L21).
Maybe don't lable the Plugin as Bukkit universal if its limited to the paperapi so users wont get confused.

**Comment by ghost** [comment]
> Maybe don't lable the Plugin as Bukkit universal if its limited to the paperapi so users wont get confused.

Thanks for the feedback. I won't change the name, but instead I won't block the plugin enabling if PaperMC is not used. Simply modern messages will not be formatted (because minimessage is only included in PaperMC).
