### ISSUE TITLE
[Feature Request]: Server configuration to limit the visibility distance of pings & add a cooldown

### ISSUE THREAD

**Issue by NoThrottle** [LukenSkyne/Minecraft-Ping-Wheel#12]
What it might look like:

Ping data is sent to all players. However, if the server specifies a max distance, players that are farther than that distance from a ping, won't be shown and they will not be notified. 

Also maybe a way to have a ping cool down where if a players pings more than X number of times in Y amount of time, they will get a Z seconds time out before they can ping again.

**Comment by RXJpaw** [comment]
This already is a client-side feature for everyone to set for themselves.
Please visit the config menu by writing `/pingwheel config` or visiting the modmenu-integration.

If players want to see further away pings, they should be able to decide for themselves.
Restricting the players by enforcing a server-wide limit is not a planned feature.

A cooldown (client-/server-side) is a more requested feature and we may implement this at some point but at this time such feature is not planned as the mod is supposed to be used in smaller groups.

If you are annoyed by users abusing pings please set a channel with `/pingwheel config` and share the channel with your friends.
