### ISSUE TITLE
[Bug]: Clients without the mod are unable to join the Server

### ISSUE THREAD

**Issue by Strl3aker** [LukenSkyne/Minecraft-Ping-Wheel#13]
Request support for non mandatory use of mod by the client, that is, optional installation by the client after the server is installed, not mandatory installation. The server data is only provided to users who install similar mod and users who have not been installed are not affected....
I don't know if this can be achieved, but I hope to have this feature. Or it has been implemented but I haven't found any configuration features..
Thank you for your hard work. I really like this mod!!!

**Comment by RXJpaw** [comment]
I'm sorry but the translation tool you currently use is not doing you a big favour here. But I'll try interpreting your request.

What I understand is you want players to see pings even if they don't have the mod installed, if the mod is installed on the server, right? But this is not possible, Minecraft doesn't allow such thing to exist.

If this isn't your request, please rephrase your issue or provide the issue in your native language so we can try translating and resolving your issue.

**Comment by RXJpaw** [comment]
What I found out is that the server forces the player to have PingWheel installed, which makes users without the mod unable to join. This is an unwanted behaviour and we try to resolve your issue soon.

**Comment by Strl3aker** [comment]
I think the submitted issue is consistent with the BUG you found, and it bothers me that users who don't have the mod can't join the server because not all users are willing to install the Mod

**Comment by Strl3aker** [comment]
You have understood what I want  andto express marked it as a BUG. I think users should not be forces have PingWheel installed. Thank you very much for your patient answer

**Comment by LukenSkyne** [comment]
The bug should now be resolved in the 1.3.1 release.
If you still have the issue with the newest version, please let me know what version of minecraft + modpack you used.

**Comment by Strl3aker** [comment]
Oh, I have already used 1.3.1 release and there are currently no issues! Thank you.XD
