### ISSUE TITLE
Client-side only

### ISSUE THREAD

**Issue by csutora** [LukenSkyne/Minecraft-Ping-Wheel#14]
Hi! I'm looking to write a mod that's similar to yours but completely client-side (i'm thinking of using specific chat messages to communicate between clients, that are understandable by non-mod-users as well, like "playername pinged 200 67 -186")

My question is, do you want to collaborate on this and add it as a feature to your mod, or shall I just write my own?
There could just be a toggle in modmenu to change how it communicates with others (through server-side mod or chat)

**Comment by RXJpaw** [comment]
Hey!

One problem is that by using a serverless communication system (without external servers as described below) it would be impossible for users to declare channels for private communication. So everyone would receive everyone's message.

If considering making a mod that can be used without direct server communication, it may be more practical if you host external servers for users to connect to and send their packets including current server-ip-address and channel to, distributing them correctly, without a server-side mod needed.

Using "external servers" was the first implementation we thought of when creating Ping Wheel, but we put user experience first and decided to use server-sided mods for communication between clients. This approach has a benefit to server owners as they can decide if Ping Wheel should be supported by activly uploading the mod to their server.

In my opinion using the chat is the wrong approach to pinging and not exactly user-friendly. And talking with Luken about the idea, we couldn't think of how to support user-friendly chat-only communication with the features we already provide. But you are free to create your own Ping Wheel-fork.

**Comment by YoshiRulz** [comment]
Given that this isn't planned, can you add an option for the mod to disable itself when opening to LAN from singleplayer?

**Comment by LukenSkyne** [comment]
> can you add an option for the mod to disable itself when opening to LAN from singleplayer?

I am not aware of any issues the mod is causing when opening from singleplayer to LAN. Please open a separate issue and elaborate on your thoughts.

**Comment by YoshiRulz** [comment]
My bad, it turns out it only prevents clients *with the Fabric API but without Ping Wheel* from joining. Vanilla clients can join fine.

[This fork](https://modrinth.com/mod/mcpings) doesn't have the same problem so I'll just use that.
