### ISSUE TITLE
Not working 1.20.1

### ISSUE THREAD

**Issue by ClassyCustom** [LukenSkyne/Minecraft-Ping-Wheel#20]
Im having an issue where I can't make any pings I've confirmed that im using the correct version and I've set a channel in the config.

**Comment by RXJpaw** [comment]
We've confirmed that our mod works with 1.20.1.

Please provide us with following information:
* Did you confirm you're using the correct keybindings?
* What mods are you using in combination with Ping Wheel?
* Did this occur in Singleplayer or Multiplayer?

Please note that using Ping Wheel on servers only works when Ping Wheel is also installed on the corresponding server.

**Comment by ClassyCustom** [comment]
Yeah my bad i was trying to use it in multiplayer
