### ISSUE TITLE
[Bug]: Language / Encoding problem

### ISSUE THREAD

**Issue by qurle** [LukenSkyne/Minecraft-Ping-Wheel#22]
### Preflight Checklist

- [X] I am using the [latest version](https://github.com/LukenSkyne/Minecraft-Ping-Wheel/releases) of Ping Wheel.
- [X] The server I am playing on has Ping Wheel installed.
- [X] I have searched the [issue tracker](https://github.com/LukenSkyne/Minecraft-Ping-Wheel/issues?q=is%3Aissue) for a bug report that matches the one I want to file, without success.

### What versions of Minecraft have you experienced the issue in?

1.19.4

### Expected Behavior

After placing mod in `.minecraft/mods` both on client and server, I just wanted to launch Minecraft and play.

### Actual Behavior

After opening Minecraft client every text characters appears as rectangle symbol. I guess, there only one language left.

![image](https://github.com/LukenSkyne/Minecraft-Ping-Wheel/assets/32414396/9552daa9-8bf8-4547-8292-56a435f1fe00)
![image](https://github.com/LukenSkyne/Minecraft-Ping-Wheel/assets/32414396/a32b75c5-25ea-4895-8410-32efa759d992)

### Additional Information

After removing mod from `mods` folder, everything returns back to normal state.
I use Fabric Loader v0.14.24 and Ping Wheel v1.5.1

**Comment by RXJpaw** [comment]
Could not replicate with: Windows 10.0.19045.3570, Java 17.0.8, Minecraft 1.19.4, Fabric Loader v0.14.24, Fabric API v0.87.1, Ping Wheel v1.5.1

**Comment by RXJpaw** [comment]
Have you tried creating a new Minecraft Instance with all settings reset? If not; try renaming your `.minecraft`-folder to `.minecraft2` and repeat the process. If this works, the problem is likely to be caused by settings saved in your profiles.

I have found following alternative solutions of people with similar issues:
* if OptiFabric is installed, remove and use Sodium instead (+ Iris for shaders)
* update your graphics card driver

If your issue persists please send us your log, located at `.minecraft/logs/latest.log`.

**Comment by RXJpaw** [comment]
I have found following solutions of people with similar issues:
* if OptiFabric is installed, remove and use Sodium instead (+ Iris for shaders)
* update your graphics card driver

**Comment by qurle** [comment]
Thanks a lot for your comments. That was really fast answer! 
Yeah, I got OptiFabric installed and this probalby caused an issue.
As I found out, **installing old version of Fabric API (used 0.77.0) makes everything work** as expected. 

Appreciate your help and thanks for working on this cool plugin. I guess, issue's resolved.

**Comment by RXJpaw** [comment]
Can you confirm removing OptiFabric would've resolved your issue with the initial mod configuration?

**Comment by qurle** [comment]
Tried this now. Uninstalling OptiFabric helps too.

**Comment by RXJpaw** [comment]
Thank you for confirming this for future people with similar issues!
