### ISSUE TITLE
[Migration Request]: 1.16.5 backport?

### ISSUE THREAD

**Issue by gundami** [LukenSkyne/Minecraft-Ping-Wheel#29]
this is a fantastic mod, can you backport it to 1.16.5? i'm not familiar with 1.16.5 yarn, so i can't do it by myself

**Comment by LukenSkyne** [comment]
I am currently not planning to support versions older than 1.18, since it drastically increases the required maintenance. Also most of the modded playerbase is currently found in 1.19/1.20 and will shift to newer versions eventually.
