### ISSUE TITLE
[Feature Request]: Plugin form for Paper

### ISSUE THREAD

**Issue by TheCrafter8000** [LukenSkyne/Minecraft-Ping-Wheel#31]
it would be nice to see a server side plugin so this mod can work on paper servers

**Comment by LukenSkyne** [comment]
You can find the plugin version of Ping Wheel on [GitHub](https://github.com/RXJpaw/Minecraft-Ping-Wheel-Plugin/), [CurseForge](https://www.curseforge.com/minecraft/bukkit-plugins/ping-wheel-plugin) and [Modrinth](https://modrinth.com/plugin/ping-wheel-plugin). Enjoy!
