### ISSUE TITLE
[Feature Request]: infinite ping duration;glow effect;remove ping

### ISSUE THREAD

**Issue by felicia1the1goat** [LukenSkyne/Minecraft-Ping-Wheel#34]
id would be a cool feature if you could select the ping to be permanent by settings the slider all the way to the max, also would be cool if the entity/item would glow through walls and also if you could remove a ping by pressing the ping button while looking at a ping and maybe a settings to select the "radius" of the ping you have to look t to remove it. would be realy cool if those features would get qadded :D

**Comment by LukenSkyne** [comment]
> set the ping to be permanent

This is similar to the request in #33. I've noted it down that I can apply this to the ping duration as well!

> also would be cool if the entity/item would glow through walls

This has been requested before (#16). It is actually easy to do but I really don't like the vanilla glow effect. I've experimented with adding a custom shader to render my own outline, but it is not without flaws yet. Can't tell when or if this is going to be added :P

> you could remove a ping by pressing the ping button while looking at it

This mostly makes sense with infinite pings, I'll think about it 🤔

**Comment by LukenSkyne** [comment]
Since the glow effect was requested by another issue, I am closing this one.
The infinite ping duration & ability to remove pings is introduced in v1.9.0 🎉
