### ISSUE TITLE
[Feature Request]: Update for 1.20.6

### ISSUE THREAD

**Issue by EgorkaSanyok** [LukenSkyne/Minecraft-Ping-Wheel#37]
Hi there! First of all, thank you for developing such an awesome mod, it's extremely useful!
I would like to know if there are plans of updating it to 1.20.6 anytime soon? It's one of the essential mods that I would wait for, before upgrading to 1.20.6!

**Comment by LukenSkyne** [comment]
Hey, glad you like the project! ⭐

Working on it. Fabric is basically finished, but Forge is giving me a headache.
Considering switching to NeoForge as we speak...

**Comment by EgorkaSanyok** [comment]
Thank you for the update! Personally, I am using Fabric but I understand holding off on releasing until it's ready for all the loaders!

**Comment by LukenSkyne** [comment]
Thanks for your patience! Releases for 1.20.6 are now available :)
