### ISSUE TITLE
1.18.2 backport?

### ISSUE THREAD

**Issue by ConqAra** [LukenSkyne/Minecraft-Ping-Wheel#4]
A backport would be amazing, this is really really helpful, I hope you can port it to 1.18.2!

**Comment by LukenSkyne** [comment]
Done! [Curseforge](https://www.curseforge.com/minecraft/mc-mods/ping-wheel/files/all?filter-game-version=1738749986%3a73250) & [Modrinth](https://modrinth.com/mod/ping-wheel/version/1.1.0-1.18+1.18.1+1.18.2)
