### ISSUE TITLE
[Bug]: I can't ping anything on my multiplayer server

### ISSUE THREAD

**Issue by Choopie1** [LukenSkyne/Minecraft-Ping-Wheel#44]
### Preflight Checklist

- [X] I am using the [latest version](https://github.com/LukenSkyne/Minecraft-Ping-Wheel/releases) of Ping Wheel for the corresponding mod loader.
- [X] The server I am playing on has Ping Wheel installed.
- [x] I have searched the [issue tracker](https://github.com/LukenSkyne/Minecraft-Ping-Wheel/issues?q=is%3Aissue) for a bug report that matches the one I want to file, without success.

### Which mod loaders have you experienced the issue with?

Forge

### What versions of Minecraft have you experienced the issue in?

1.21

### Expected Behavior

I expected to be able to place a ping that myself and other players can see.

### Actual Behavior

When pressing the assigned key to place the ping, nothing happens.

### Logs URL

https://mclo.gs/F5my7Wh

### Additional Information

Works just fine in singleplayer, nobody in my multiplayer world is able to place pings either. Also, when the default channel is disabled and I am using the default channel to place a ping, I get an error. But when I switch to another channel, I still can't place a ping, despite there being no error message anymore.

**Comment by LukenSkyne** [comment]
Thanks for bringing this to my attention!
I have confirmed that this affects the Forge Server for Minecraft 1.21 and 1.20.6.
Fix on the way!

**Comment by LukenSkyne** [comment]
Should be fixed in v1.9.2 for both forge 1.21 and 1.20.6! 🎉
Feel free to re-open the issue if the problem persists!

**Comment by Artasov** [comment]
Проблема такая же на версии 1.20.1 Fabric.
