### ISSUE TITLE
1.19.3 update?

### ISSUE THREAD

**Issue by lostopkk** [LukenSkyne/Minecraft-Ping-Wheel#5]

**Comment by LukenSkyne** [comment]
I will give it a shot. Please keep in mind that Mojang changed a lot of the internals with 1.19.3 ([see here](https://fabricmc.net/2022/11/24/1193.html)) which makes it rather difficult.

**Comment by LukenSkyne** [comment]
Done! [Curseforge](https://www.curseforge.com/minecraft/mc-mods/ping-wheel/files/all?filter-game-version=2020709689%3A9550) & [Modrinth](https://modrinth.com/mod/ping-wheel/versions)
