### ISSUE TITLE
Migration Request Forge [1.19.2]

### ISSUE THREAD

**Issue by Looodon** [LukenSkyne/Minecraft-Ping-Wheel#6]
Hey,
I'd love if you made this for forge! the forge mod you got inspired by isn't getting updated and doesn't work with shaders.
Thanks,

**Comment by LukenSkyne** [comment]
I am not sure how different forge modding is from fabric, but either way I will have to migrate to 1.19.3 first.

**Comment by Looodon** [comment]
If you do plan to migrate it to forge, id appreciate a 1.19.2 version :) 👍

**Comment by Wubzzz1337** [comment]
1.19.2 version would make more sense since more mods are on that version :o!
So please, this mod is cool!

**Comment by BWP09** [comment]
it would be amazing if this mod had a forge version!

**Comment by LukenSkyne** [comment]
Glad to announce that the mod is now finally cross platform with v1.6.0 and thus available on forge!
