### ISSUE TITLE
Question about a 'fork'

### ISSUE THREAD

**Issue by Dyvinia** [LukenSkyne/Minecraft-Ping-Wheel#9]
Hi, I'm generally a huge fan of pinging systems in games so I love this mod! 
I'm not sure where I could ask you this, but I'm currently in the process of rewriting it purely in java as I'm currently learning java; I've also made a few changes and I was wondering if I'd be allowed to publish it as a mod (with credit)

**Comment by LukenSkyne** [comment]
Hey, very kind of you to ask!
Sure you can do whatever you feel like, if you think that our versions should co-exist you might as well publish yours. 😇
